# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5387816a53a3a7e4126baabac69977374419ea7db7b06f7a9dc8018e90c2364af90ec28e54db4692d5a1114565558ad5d5f4ce24515f97298e6e091ac13e17e

test:
  secret_key_base: 03511e0e5c740246a03b63570ebdc661c37c8b25b3b381a4d8de3b526d7df5b8345425d033dea4c707fc9a74bf95e4384ab4dd6d0ea0642ba7770fe8a29b4fec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
